TARGET	= libmatmult.so
LIBSRCS	= matmultlib.c
LIBOBJS	= $(LIBSRCS:.c=.o)

OPT     = -g -O3 -ffast-math -funroll-loops -fopt-info
PIC	= -fPIC

CC      = gcc
CFLAGS  = $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared 
XLIBS	= -L/usr/lib64/atlas -lsatlas

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS) 
